/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as ClassroomsRouteImport } from './routes/classrooms'
import { Route as DevicesRouteImport } from './routes/devices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomsRoute = ClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/devices': typeof DevicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/devices': typeof DevicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/buildings': typeof BuildingsRoute
  '/classrooms': typeof ClassroomsRoute
  '/devices': typeof DevicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/analytics'
    | '/buildings'
    | '/classrooms'
    | '/devices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/analytics'
    | '/buildings'
    | '/classrooms'
    | '/devices'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/analytics'
    | '/buildings'
    | '/classrooms'
    | '/devices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuildingsRoute: typeof BuildingsRoute
  ClassroomsRoute: typeof ClassroomsRoute
  DevicesRoute: typeof DevicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classrooms': {
      id: '/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof ClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuildingsRoute: BuildingsRoute,
  ClassroomsRoute: ClassroomsRoute,
  DevicesRoute: DevicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
